@startuml

skinparam componentStyle uml2

package "'Person' Aggregate" <<Rectangle>> {
	class Person <<(A,#fffab8) Aggregate Root>> {
		String name
		Date dateOfBirth
		PersonId id
		Cpf cpf
		Email contactEmail
	}
	class PersonId <<(V,DarkSeaGreen) Value Object>> {
		int id
	}
	class Cpf <<(V,DarkSeaGreen) Value Object>> {
		String cpf
	}
	class Email <<(V,DarkSeaGreen) Value Object>> {
		String emailText
	}
}
package "'Patient' Aggregate" <<Rectangle>> {
	class Patient <<(A,#fffab8) Aggregate Root>> {
		List<String> patientConditions
		PatientId id
		List<ResultId> results
	}
	class PatientId <<(V,DarkSeaGreen) Value Object>> {
		int id
	}
}
package "'Doctor' Aggregate" <<Rectangle>> {
	class Doctor <<(A,#fffab8) Aggregate Root>> {
		DoctorId id
	}
	class DoctorId <<(V,DarkSeaGreen) Value Object>> {
		int id
	}
}
package "'Test' Aggregate" <<Rectangle>> {
	class Test <<(A,#fffab8) Aggregate Root>> {
		String name
		String descriptionText
		TestId id
	}
	class TestId <<(V,DarkSeaGreen) Value Object>> {
		int id
	}
}
package "'Appointment' Aggregate" <<Rectangle>> {
	class Appointment <<(A,#fffab8) Aggregate Root>> {
		Date dateOfAppointment
		AppointmentId id
		PatientId patientId
		DoctorId doctorId
	}
	class AppointmentId <<(V,DarkSeaGreen) Value Object>> {
		int id
	}
}
package "'Result' Aggregate" <<Rectangle>> {
	class Result <<(A,#fffab8) Aggregate Root>> {
		String contentOfResult
		ResultId id
		TestId test
	}
	class ResultId <<(V,DarkSeaGreen) Value Object>> {
		int id
	}
}
Test --> TestId : id
Person --> Email : contactEmail
Result --> ResultId : id
Appointment --> AppointmentId : id
Appointment --> DoctorId : doctorId
Person --> PersonId : id
Patient "1" o--> "*" ResultId : results
Result --> TestId : test
Appointment --> PatientId : patientId
Person --> Cpf : cpf
Patient --> PatientId : id
Doctor --> DoctorId : id
Patient --|> Person
Doctor --|> Person
legend left
  This bounded context implements the subdomain 'Administration'.
  This bounded context implements the subdomain 'Testing'.
  This bounded context implements the subdomain 'Results'.
end legend


@enduml
