@startuml

skinparam componentStyle uml2

package "'Test' Aggregate" <<Rectangle>> {
	class Test <<(A,#fffab8) Aggregate Root>> {
		String name
		String descriptionText
		TestId id
	}
	class TestId <<(V,DarkSeaGreen) Value Object>> {
		int id
	}
}
Test --> TestId : id


@enduml
