
    create table attendants (
        id bigint not null,
        password varchar(255),
        primary key (id)
    );

    create table clients (
        client_service_id bigint generated by default as identity,
        exam_request_id bigint unique,
        id bigint not null,
        service_number_id bigint unique,
        status varchar(255),
        primary key (client_service_id)
    );

    create table exam_request (
        request_date date not null,
        total_price float(53),
        client_id bigint,
        exam_request_id bigint generated by default as identity,
        payment_method varchar(255) not null,
        status varchar(255) not null,
        primary key (exam_request_id)
    );

    create table exams (
        analysis_time integer,
        price float(53),
        id bigint generated by default as identity,
        name varchar(255),
        requirements varchar(255),
        primary key (id)
    );

    create table exam_test (
        exam_id bigint,
        exam_test_id bigint generated by default as identity,
        service_number_id bigint,
        test_result_id bigint unique,
        status varchar(255),
        primary key (exam_test_id)
    );

    create table financial_overview (
        insurance_payments integer not null,
        private_payments integer not null,
        financial_overview_id bigint generated by default as identity,
        primary key (financial_overview_id)
    );

    create table people (
        birth_date date,
        id bigint generated by default as identity,
        contact_email varchar(255),
        cpf varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table service_number (
        is_priority boolean not null,
        id bigint generated by default as identity,
        number varchar(255),
        status varchar(255),
        primary key (id)
    );

    create table test_result (
        result_date date not null,
        test_result_id bigint generated by default as identity,
        result_content varchar(255),
        primary key (test_result_id)
    );

    alter table if exists attendants 
       add constraint FKpfkslasdk918vyu3qwrsuum2w 
       foreign key (id) 
       references people;

    alter table if exists clients 
       add constraint FKbv6l6ra9f14nuketg8iohf1sp 
       foreign key (exam_request_id) 
       references exam_request;

    alter table if exists clients 
       add constraint FKgwkhgdqxne6vpr7sul3an4lx9 
       foreign key (service_number_id) 
       references service_number;

    alter table if exists clients 
       add constraint FKkujwxi9ys82vxhwt5m6u4ico8 
       foreign key (id) 
       references people;

    alter table if exists exam_request 
       add constraint FKnohkmft2wt9p7trvnrg6ssqin 
       foreign key (client_id) 
       references clients;

    alter table if exists exam_test 
       add constraint FKhimpkmg65dpj7n3qd8nys6ejs 
       foreign key (exam_id) 
       references exams;

    alter table if exists exam_test 
       add constraint FKl8ckoik7j4d5ktpgqxge4dfvt 
       foreign key (test_result_id) 
       references test_result;

    alter table if exists exam_test 
       add constraint FK3cxdarm2j6l88vmegopqrk80j 
       foreign key (service_number_id) 
       references exam_request;

    create table attendants (
        id bigint not null,
        password varchar(255),
        primary key (id)
    );

    create table clients (
        client_service_id bigint generated by default as identity,
        exam_request_id bigint unique,
        id bigint not null,
        service_number_id bigint unique,
        status varchar(255),
        primary key (client_service_id)
    );

    create table exam_request (
        request_date date not null,
        total_price float(53),
        client_id bigint,
        exam_request_id bigint generated by default as identity,
        payment_method varchar(255) not null,
        status varchar(255) not null,
        primary key (exam_request_id)
    );

    create table exams (
        analysis_time integer,
        price float(53),
        id bigint generated by default as identity,
        name varchar(255),
        requirements varchar(255),
        primary key (id)
    );

    create table exam_test (
        exam_id bigint,
        exam_test_id bigint generated by default as identity,
        service_number_id bigint,
        test_result_id bigint unique,
        status varchar(255),
        primary key (exam_test_id)
    );

    create table financial_overview (
        insurance_payments integer not null,
        private_payments integer not null,
        financial_overview_id bigint generated by default as identity,
        primary key (financial_overview_id)
    );

    create table people (
        birth_date date,
        id bigint generated by default as identity,
        contact_email varchar(255),
        cpf varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table service_number (
        is_priority boolean not null,
        id bigint generated by default as identity,
        number varchar(255),
        status varchar(255),
        primary key (id)
    );

    create table test_result (
        result_date date not null,
        test_result_id bigint generated by default as identity,
        result_content varchar(255),
        primary key (test_result_id)
    );

    alter table if exists attendants 
       add constraint FKpfkslasdk918vyu3qwrsuum2w 
       foreign key (id) 
       references people;

    alter table if exists clients 
       add constraint FKbv6l6ra9f14nuketg8iohf1sp 
       foreign key (exam_request_id) 
       references exam_request;

    alter table if exists clients 
       add constraint FKgwkhgdqxne6vpr7sul3an4lx9 
       foreign key (service_number_id) 
       references service_number;

    alter table if exists clients 
       add constraint FKkujwxi9ys82vxhwt5m6u4ico8 
       foreign key (id) 
       references people;

    alter table if exists exam_request 
       add constraint FKnohkmft2wt9p7trvnrg6ssqin 
       foreign key (client_id) 
       references clients;

    alter table if exists exam_test 
       add constraint FKhimpkmg65dpj7n3qd8nys6ejs 
       foreign key (exam_id) 
       references exams;

    alter table if exists exam_test 
       add constraint FKl8ckoik7j4d5ktpgqxge4dfvt 
       foreign key (test_result_id) 
       references test_result;

    alter table if exists exam_test 
       add constraint FK3cxdarm2j6l88vmegopqrk80j 
       foreign key (service_number_id) 
       references exam_request;

    create table attendants (
        id bigint not null,
        password varchar(255),
        primary key (id)
    );

    create table clients (
        client_service_id bigint generated by default as identity,
        exam_request_id bigint unique,
        id bigint not null,
        service_number_id bigint unique,
        status varchar(255),
        primary key (client_service_id)
    );

    create table exam_request (
        request_date date not null,
        total_price float(53),
        client_id bigint,
        exam_request_id bigint generated by default as identity,
        payment_method varchar(255) not null,
        status varchar(255) not null,
        primary key (exam_request_id)
    );

    create table exams (
        analysis_time integer,
        price float(53),
        id bigint generated by default as identity,
        name varchar(255),
        requirements varchar(255),
        primary key (id)
    );

    create table exam_test (
        exam_id bigint,
        exam_test_id bigint generated by default as identity,
        service_number_id bigint,
        test_result_id bigint unique,
        status varchar(255),
        primary key (exam_test_id)
    );

    create table financial_overview (
        insurance_payments integer not null,
        private_payments integer not null,
        financial_overview_id bigint generated by default as identity,
        primary key (financial_overview_id)
    );

    create table people (
        birth_date date,
        id bigint generated by default as identity,
        contact_email varchar(255),
        cpf varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table service_number (
        is_priority boolean not null,
        id bigint generated by default as identity,
        number varchar(255),
        status varchar(255),
        primary key (id)
    );

    create table test_result (
        result_date date not null,
        test_result_id bigint generated by default as identity,
        result_content varchar(255),
        primary key (test_result_id)
    );

    alter table if exists attendants 
       add constraint FKpfkslasdk918vyu3qwrsuum2w 
       foreign key (id) 
       references people;

    alter table if exists clients 
       add constraint FKbv6l6ra9f14nuketg8iohf1sp 
       foreign key (exam_request_id) 
       references exam_request;

    alter table if exists clients 
       add constraint FKgwkhgdqxne6vpr7sul3an4lx9 
       foreign key (service_number_id) 
       references service_number;

    alter table if exists clients 
       add constraint FKkujwxi9ys82vxhwt5m6u4ico8 
       foreign key (id) 
       references people;

    alter table if exists exam_request 
       add constraint FKnohkmft2wt9p7trvnrg6ssqin 
       foreign key (client_id) 
       references clients;

    alter table if exists exam_test 
       add constraint FKhimpkmg65dpj7n3qd8nys6ejs 
       foreign key (exam_id) 
       references exams;

    alter table if exists exam_test 
       add constraint FKl8ckoik7j4d5ktpgqxge4dfvt 
       foreign key (test_result_id) 
       references test_result;

    alter table if exists exam_test 
       add constraint FK3cxdarm2j6l88vmegopqrk80j 
       foreign key (service_number_id) 
       references exam_request;

    create table attendants (
        id bigint not null,
        password varchar(255),
        primary key (id)
    );

    create table clients (
        client_service_id bigint generated by default as identity,
        exam_request_id bigint unique,
        id bigint not null,
        service_number_id bigint unique,
        status varchar(255),
        primary key (client_service_id)
    );

    create table exam_request (
        request_date date not null,
        total_price float(53),
        client_id bigint,
        exam_request_id bigint generated by default as identity,
        payment_method varchar(255) not null,
        status varchar(255) not null,
        primary key (exam_request_id)
    );

    create table exams (
        analysis_time integer,
        price float(53),
        id bigint generated by default as identity,
        name varchar(255),
        requirements varchar(255),
        primary key (id)
    );

    create table exam_test (
        exam_id bigint,
        exam_test_id bigint generated by default as identity,
        service_number_id bigint,
        test_result_id bigint unique,
        status varchar(255),
        primary key (exam_test_id)
    );

    create table financial_overview (
        insurance_payments integer not null,
        private_payments integer not null,
        financial_overview_id bigint generated by default as identity,
        primary key (financial_overview_id)
    );

    create table people (
        birth_date date,
        id bigint generated by default as identity,
        contact_email varchar(255),
        cpf varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table service_number (
        is_priority boolean not null,
        id bigint generated by default as identity,
        number varchar(255),
        status varchar(255),
        primary key (id)
    );

    create table test_result (
        result_date date not null,
        test_result_id bigint generated by default as identity,
        result_content varchar(255),
        primary key (test_result_id)
    );

    alter table if exists attendants 
       add constraint FKpfkslasdk918vyu3qwrsuum2w 
       foreign key (id) 
       references people;

    alter table if exists clients 
       add constraint FKbv6l6ra9f14nuketg8iohf1sp 
       foreign key (exam_request_id) 
       references exam_request;

    alter table if exists clients 
       add constraint FKgwkhgdqxne6vpr7sul3an4lx9 
       foreign key (service_number_id) 
       references service_number;

    alter table if exists clients 
       add constraint FKkujwxi9ys82vxhwt5m6u4ico8 
       foreign key (id) 
       references people;

    alter table if exists exam_request 
       add constraint FKnohkmft2wt9p7trvnrg6ssqin 
       foreign key (client_id) 
       references clients;

    alter table if exists exam_test 
       add constraint FKhimpkmg65dpj7n3qd8nys6ejs 
       foreign key (exam_id) 
       references exams;

    alter table if exists exam_test 
       add constraint FKl8ckoik7j4d5ktpgqxge4dfvt 
       foreign key (test_result_id) 
       references test_result;

    alter table if exists exam_test 
       add constraint FK3cxdarm2j6l88vmegopqrk80j 
       foreign key (service_number_id) 
       references exam_request;

    create table attendants (
        id bigint not null,
        password varchar(255),
        primary key (id)
    );

    create table clients (
        client_service_id bigint generated by default as identity,
        exam_request_id bigint unique,
        id bigint not null,
        service_number_id bigint unique,
        status varchar(255),
        primary key (client_service_id)
    );

    create table exam_request (
        request_date date not null,
        total_price float(53),
        client_id bigint,
        exam_request_id bigint generated by default as identity,
        payment_method varchar(255) not null,
        status varchar(255) not null,
        primary key (exam_request_id)
    );

    create table exams (
        analysis_time integer,
        price float(53),
        id bigint generated by default as identity,
        name varchar(255),
        requirements varchar(255),
        primary key (id)
    );

    create table exam_test (
        exam_id bigint,
        exam_test_id bigint generated by default as identity,
        service_number_id bigint,
        test_result_id bigint unique,
        status varchar(255),
        primary key (exam_test_id)
    );

    create table financial_overview (
        insurance_payments integer not null,
        private_payments integer not null,
        financial_overview_id bigint generated by default as identity,
        primary key (financial_overview_id)
    );

    create table people (
        birth_date date,
        id bigint generated by default as identity,
        contact_email varchar(255),
        cpf varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table service_number (
        is_priority boolean not null,
        id bigint generated by default as identity,
        number varchar(255),
        status varchar(255),
        primary key (id)
    );

    create table test_result (
        result_date date not null,
        test_result_id bigint generated by default as identity,
        result_content varchar(255),
        primary key (test_result_id)
    );

    alter table if exists attendants 
       add constraint FKpfkslasdk918vyu3qwrsuum2w 
       foreign key (id) 
       references people;

    alter table if exists clients 
       add constraint FKbv6l6ra9f14nuketg8iohf1sp 
       foreign key (exam_request_id) 
       references exam_request;

    alter table if exists clients 
       add constraint FKgwkhgdqxne6vpr7sul3an4lx9 
       foreign key (service_number_id) 
       references service_number;

    alter table if exists clients 
       add constraint FKkujwxi9ys82vxhwt5m6u4ico8 
       foreign key (id) 
       references people;

    alter table if exists exam_request 
       add constraint FKnohkmft2wt9p7trvnrg6ssqin 
       foreign key (client_id) 
       references clients;

    alter table if exists exam_test 
       add constraint FKhimpkmg65dpj7n3qd8nys6ejs 
       foreign key (exam_id) 
       references exams;

    alter table if exists exam_test 
       add constraint FKl8ckoik7j4d5ktpgqxge4dfvt 
       foreign key (test_result_id) 
       references test_result;

    alter table if exists exam_test 
       add constraint FK3cxdarm2j6l88vmegopqrk80j 
       foreign key (service_number_id) 
       references exam_request;

    create table attendants (
        id bigint not null,
        password varchar(255),
        primary key (id)
    );

    create table clients (
        client_service_id bigint generated by default as identity,
        exam_request_id bigint unique,
        id bigint not null,
        service_number_id bigint unique,
        status varchar(255),
        primary key (client_service_id)
    );

    create table exam_request (
        request_date date not null,
        total_price float(53),
        client_id bigint,
        exam_request_id bigint generated by default as identity,
        payment_method varchar(255) not null,
        status varchar(255) not null,
        primary key (exam_request_id)
    );

    create table exams (
        analysis_time integer,
        price float(53),
        id bigint generated by default as identity,
        name varchar(255),
        requirements varchar(255),
        primary key (id)
    );

    create table exam_test (
        exam_id bigint,
        exam_test_id bigint generated by default as identity,
        service_number_id bigint,
        test_result_id bigint unique,
        status varchar(255),
        primary key (exam_test_id)
    );

    create table financial_overview (
        insurance_payments integer not null,
        private_payments integer not null,
        financial_overview_id bigint generated by default as identity,
        primary key (financial_overview_id)
    );

    create table people (
        birth_date date,
        id bigint generated by default as identity,
        contact_email varchar(255),
        cpf varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table service_number (
        is_priority boolean not null,
        id bigint generated by default as identity,
        number varchar(255),
        status varchar(255),
        primary key (id)
    );

    create table test_result (
        result_date date not null,
        test_result_id bigint generated by default as identity,
        result_content varchar(255),
        primary key (test_result_id)
    );

    alter table if exists attendants 
       add constraint FKpfkslasdk918vyu3qwrsuum2w 
       foreign key (id) 
       references people;

    alter table if exists clients 
       add constraint FKbv6l6ra9f14nuketg8iohf1sp 
       foreign key (exam_request_id) 
       references exam_request;

    alter table if exists clients 
       add constraint FKgwkhgdqxne6vpr7sul3an4lx9 
       foreign key (service_number_id) 
       references service_number;

    alter table if exists clients 
       add constraint FKkujwxi9ys82vxhwt5m6u4ico8 
       foreign key (id) 
       references people;

    alter table if exists exam_request 
       add constraint FKnohkmft2wt9p7trvnrg6ssqin 
       foreign key (client_id) 
       references clients;

    alter table if exists exam_test 
       add constraint FKhimpkmg65dpj7n3qd8nys6ejs 
       foreign key (exam_id) 
       references exams;

    alter table if exists exam_test 
       add constraint FKl8ckoik7j4d5ktpgqxge4dfvt 
       foreign key (test_result_id) 
       references test_result;

    alter table if exists exam_test 
       add constraint FK3cxdarm2j6l88vmegopqrk80j 
       foreign key (service_number_id) 
       references exam_request;

    create table attendants (
        id bigint not null,
        password varchar(255),
        primary key (id)
    );

    create table clients (
        client_service_id bigint generated by default as identity,
        exam_request_id bigint unique,
        id bigint not null,
        service_number_id bigint unique,
        status varchar(255),
        primary key (client_service_id)
    );

    create table exam_request (
        request_date date not null,
        total_price float(53),
        client_id bigint,
        exam_request_id bigint generated by default as identity,
        payment_method varchar(255) not null,
        status varchar(255) not null,
        primary key (exam_request_id)
    );

    create table exams (
        analysis_time integer,
        price float(53),
        id bigint generated by default as identity,
        name varchar(255),
        requirements varchar(255),
        primary key (id)
    );

    create table exam_test (
        exam_id bigint,
        exam_test_id bigint generated by default as identity,
        service_number_id bigint,
        test_result_id bigint unique,
        status varchar(255),
        primary key (exam_test_id)
    );

    create table financial_overview (
        insurance_payments integer not null,
        private_payments integer not null,
        financial_overview_id bigint generated by default as identity,
        primary key (financial_overview_id)
    );

    create table people (
        birth_date date,
        id bigint generated by default as identity,
        contact_email varchar(255),
        cpf varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table service_number (
        is_priority boolean not null,
        id bigint generated by default as identity,
        number varchar(255),
        status varchar(255),
        primary key (id)
    );

    create table test_result (
        result_date date not null,
        test_result_id bigint generated by default as identity,
        result_content varchar(255),
        primary key (test_result_id)
    );

    alter table if exists attendants 
       add constraint FKpfkslasdk918vyu3qwrsuum2w 
       foreign key (id) 
       references people;

    alter table if exists clients 
       add constraint FKbv6l6ra9f14nuketg8iohf1sp 
       foreign key (exam_request_id) 
       references exam_request;

    alter table if exists clients 
       add constraint FKgwkhgdqxne6vpr7sul3an4lx9 
       foreign key (service_number_id) 
       references service_number;

    alter table if exists clients 
       add constraint FKkujwxi9ys82vxhwt5m6u4ico8 
       foreign key (id) 
       references people;

    alter table if exists exam_request 
       add constraint FKnohkmft2wt9p7trvnrg6ssqin 
       foreign key (client_id) 
       references clients;

    alter table if exists exam_test 
       add constraint FKhimpkmg65dpj7n3qd8nys6ejs 
       foreign key (exam_id) 
       references exams;

    alter table if exists exam_test 
       add constraint FKl8ckoik7j4d5ktpgqxge4dfvt 
       foreign key (test_result_id) 
       references test_result;

    alter table if exists exam_test 
       add constraint FK3cxdarm2j6l88vmegopqrk80j 
       foreign key (service_number_id) 
       references exam_request;

    create table attendants (
        id bigint not null,
        password varchar(255),
        primary key (id)
    );

    create table clients (
        client_service_id bigint generated by default as identity,
        exam_request_id bigint unique,
        id bigint not null,
        service_number_id bigint unique,
        status varchar(255),
        primary key (client_service_id)
    );

    create table exam_request (
        request_date date not null,
        total_price float(53),
        client_id bigint,
        exam_request_id bigint generated by default as identity,
        payment_method varchar(255) not null,
        status varchar(255) not null,
        primary key (exam_request_id)
    );

    create table exams (
        analysis_time integer,
        price float(53),
        id bigint generated by default as identity,
        name varchar(255),
        requirements varchar(255),
        primary key (id)
    );

    create table exam_test (
        exam_id bigint,
        exam_test_id bigint generated by default as identity,
        service_number_id bigint,
        test_result_id bigint unique,
        status varchar(255),
        primary key (exam_test_id)
    );

    create table financial_overview (
        insurance_payments integer not null,
        private_payments integer not null,
        financial_overview_id bigint generated by default as identity,
        primary key (financial_overview_id)
    );

    create table people (
        birth_date date,
        id bigint generated by default as identity,
        contact_email varchar(255),
        cpf varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table service_number (
        is_priority boolean not null,
        id bigint generated by default as identity,
        number varchar(255),
        status varchar(255),
        primary key (id)
    );

    create table test_result (
        result_date date not null,
        test_result_id bigint generated by default as identity,
        result_content varchar(255),
        primary key (test_result_id)
    );

    alter table if exists attendants 
       add constraint FKpfkslasdk918vyu3qwrsuum2w 
       foreign key (id) 
       references people;

    alter table if exists clients 
       add constraint FKbv6l6ra9f14nuketg8iohf1sp 
       foreign key (exam_request_id) 
       references exam_request;

    alter table if exists clients 
       add constraint FKgwkhgdqxne6vpr7sul3an4lx9 
       foreign key (service_number_id) 
       references service_number;

    alter table if exists clients 
       add constraint FKkujwxi9ys82vxhwt5m6u4ico8 
       foreign key (id) 
       references people;

    alter table if exists exam_request 
       add constraint FKnohkmft2wt9p7trvnrg6ssqin 
       foreign key (client_id) 
       references clients;

    alter table if exists exam_test 
       add constraint FKhimpkmg65dpj7n3qd8nys6ejs 
       foreign key (exam_id) 
       references exams;

    alter table if exists exam_test 
       add constraint FKl8ckoik7j4d5ktpgqxge4dfvt 
       foreign key (test_result_id) 
       references test_result;

    alter table if exists exam_test 
       add constraint FK3cxdarm2j6l88vmegopqrk80j 
       foreign key (service_number_id) 
       references exam_request;
