@startuml

skinparam componentStyle uml2

package "'TestResult' Aggregate" <<Rectangle>> {
	class TestResult <<(A,#fffab8) Aggregate Root>> {
		Date resultDate
		String resultContent
		TestResultId id
	}
	class TestResultId <<(V,DarkSeaGreen) Value Object>> {
		int id
	}
}
TestResult --> TestResultId : id


@enduml
