@startuml

skinparam componentStyle uml2

package "'ExamRequest' Aggregate" <<Rectangle>> {
	class ExamRequest <<(A,#fffab8) Aggregate Root>> {
		Date requestDate
		Double totalPrice
		String paymentMethod
		String status
		ExamRequestId id
		ClientId clientId
		List<ExamTestId> examTestList
	}
	class ExamRequestId <<(V,DarkSeaGreen) Value Object>> {
		int id
	}
}
ExamRequest --> ExamRequestId : id


@enduml
